convertor/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

	root 'requests#show'

	get 'convert' => 'requests#index'
	post 'convert_status' => 'requests#update_status'
	get 'files/download/:hash' => 'requests#download', as: :file_download, constraints: { hash: /[^\/]+/ }

	resources :requests
	post 'convert_ready/:file_name' => 'requests#convert_ready', constraints: { file_name: /[^\/]+/ }

	resources :users
	get 'my_requests' => 'users#show_requests', as: :my_requests
  delete 'clear_errors_requests' => 'users#clear_errors', as: :clear_errors_requests

  resources :levels
	post 'levels/upgrade/:level' => 'levels#upgrade', as: :level_upgrade

	scope 'converter_api' do
		post 'login' => 'converter_api#login'
		post 'register'=> 'converter_api#register'
		get 'get_requests/:token/:id' => 'converter_api#get_requests'
		post 'make_request' => 'converter_api#make_request'
    delete 'delete_request' => 'converter_api#delete_request'
	end

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/home', to: 'pages#home'

end

convertor/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Online Converter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
	<div class="top">
		<div class="top-left">
			online converter
		</div>
		<div class="top-right">
			<%= get_user %>
		</div>
	</div>
</div>


<div class="nav">
	<ul class="nav_menu">
		<%= nav_link "Home", home_path %>
		<% if user_signed_in? %>
			<%= nav_link "Convert", request_path(first_converter) %>
			<%= nav_link "Requests", my_requests_path %>
			<ul class="nav_menu pull-right">
				<%= nav_link "Edit profile", edit_user_registration_path %>
				<%= nav_link "Logout", destroy_user_session_path, method: :delete %>
			</ul>
		<% else %>
			<ul class="nav_menu pull-right">
				<%= nav_link "Sign up", new_user_registration_path %>
				<%= nav_link "Login", new_user_session_path %>
			</ul>
		<% end %>
		<%= nav_link "Contact", contact_path %>
		<%= nav_link "About", about_path %>
	</ul>
</div>
<div class="error_messages">
	<%= set_messages %>
</div>
<div class="banner_wrapper">
  <div class="banner_image">
  </div>
</div>

<div class="main_div">
	<%= yield %>
</div>
<div class="footerholder">
  <div class="footer">
    <p>Contact information: <a href="online.converter.inc@gmail.com">online.converter.inc@gmail.com</a>.</p>
      <p> © 2015 Online Converter, Inc. All rights reserved.</p>
  </div>
</div>
</body>
</html>