convertor/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

	root 'requests#show'

	get 'convert' => 'requests#index'
	post 'convert_status' => 'requests#update_status'
	get 'files/download/:hash' => 'requests#download', as: :file_download, constraints: { hash: /[^\/]+/ }

	resources :requests
	post 'convert_ready/:file_name' => 'requests#convert_ready', constraints: { file_name: /[^\/]+/ }

	resources :users
	get 'my_requests' => 'users#show_requests', as: :my_requests
  delete 'clear_errors_requests' => 'users#clear_errors', as: :clear_errors_requests

  resources :levels
	post 'levels/upgrade/:level' => 'levels#upgrade', as: :level_upgrade

	scope 'converter_api' do
		post 'login' => 'converter_api#login'
		post 'register'=> 'converter_api#register'
		get 'get_requests/:token/:id' => 'converter_api#get_requests'
		post 'make_request' => 'converter_api#make_request'
    delete 'delete_request' => 'converter_api#delete_request'
	end

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/home', to: 'pages#home'

end

convertor/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :requests, dependent: :destroy
	has_many :converter_apis
	belongs_to :level

	def has_requests?
		requests.newest.size < level.max_requests
	end
end

convertor/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show_requests
		@user = current_user
	end

	def clear_errors
		Request.clear_errors current_user
		redirect_to :back
	end
end

convertor/app/helpers/users_helper.rb
module UsersHelper

  def devise_error_messages_c!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

end

convertor/app/views/users/_user.html.erb
<div><%= link_to user.email, user %></div>

convertor/app/views/users/index.html.erb
<%= render @users %>

convertor/app/views/users/show.html.erb
<div style="font-size: 40px;font-weight: bold;">Requests</div>
<table border="1" style="border: 1px solid black; border-collapse: collapse;">
	<tr>
		<th>Source url</th>
		<th>Convert to</th>
		<th>Date created</th>
		<th>Status</th>	
	</tr>
	<%= render @user.requests.all %>
</table>

convertor/app/views/users/show_requests.html.erb
<center>
	<div class="table_title">Requests</div>
	<div class="clear_button_class"><button type="clear_button"><%= link_to "Clear", clear_errors_requests_path, method: :delete %></button></div>
	<table border="1" class="request_show_table">
		<tr class="table_header">
			<th>Source url</th>
			<th>Convert to</th>
			<th>Date created</th>
			<th>Status</th>	
			<th colspan="2">Action</th>
		</tr>
		<%= render @user.requests.all %>
	</table>
</center>